
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: commerce-gateway-development
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:commercegatewaydb}
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 1
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: openid, profile, email
          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope: read:user, user:email
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope: public_profile, email
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id

---

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"

---

cloudinary:
  cloud-name: dfupyxrmr
  api-key: 234171996373849
  api-secret: 3EmG-cflOJbuIKmhxjPSR4vD6YI
vnpay:
  tmn-code: T5L6K6JN
  hash-secret: HZJYFQKXJXKXWQYQWZ
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:8080/vnpay/return
  ipn-url: http://localhost:8080/vnpay/ipn
jwt:
  timeout: 10800000
  secretKey: c92a0ed7d50b0146d9dd064ffffc49b1945c8d9d236841e837bb5e4ebc08f3a1
  expiryDay: 7
  refreshKey: 1e34c845918564fa8b0559a3d32182e2bee5e41a466e1e636f795eaa97c1ed7c
  resetKey: 7f3c1b0e8a4f26d9c7e9f2d11a50384b62c1e77d9452fae8cb38d40a19f06b52






